Update embedding.po
PyDocTeur/fake-docs pull request #13
Opened 2020-11-30 10:34 UTC by JulienPalard

2020-11-30 11:18 UTC, PyDocTeur commented
Hello ! Bienvenue dans le monde merveilleux de la traduction de la documentation de Python !
Je suis PyDocteur, le robot amical qui s'occupe d'automatiser certaines taches.
Si tu as des questions, n'hésite pas à ping @JulienPalard ou @Seluj78

---
<details>
  <summary>Disclaimer</summary>

Je suis un robot fait par l'équipe de [l'AFPy et de Traduction](https://github.com/AFPy/PyDocTeur/graphs/contributors)
sur leur temps libre. Je risque de dire des bétises. Ne me blâmez pas, blamez les développeurs.

[Code source](https://github.com/afpy/pydocteur)

I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free
time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

(state: greetings)
`PyDocTeur v1.5.1
`

</details>

2020-11-30 11:20 UTC, PyDocTeur commented
Je mergerai cette PR dès que les tests passeront et qu'elle sera approuvée.

---
<details>
  <summary>Disclaimer</summary>

Je suis un robot fait par l'équipe de [l'AFPy et de Traduction](https://github.com/AFPy/PyDocTeur/graphs/contributors)
sur leur temps libre. Je risque de dire des bétises. Ne me blâmez pas, blamez les développeurs.

[Code source](https://github.com/afpy/pydocteur)

I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free
time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

(state: automerge)
`PyDocTeur v1.5.1
`

</details>

2020-12-02 09:43 UTC, Seluj78 requested changes

2020-12-02 09:43 UTC, Seluj78 commented on extending/embedding.po
> +msgstr "Proutter les valeurs de l'appel Python pour le C."
1

2020-12-02 09:43 UTC, Seluj78 requested changes

2020-12-02 09:43 UTC, Seluj78 commented on extending/embedding.po
> +msgstr "Proutter les valeurs de l'appel Python pour le C."
```suggestion
msgstr "Convertir les valeurs de l'appel Python pour le C."
```

2020-12-02 09:44 UTC, Seluj78 requested changes

2020-12-02 09:44 UTC, Seluj78 commented on extending/embedding.po
> -msgstr "Convertir les valeurs de l'appel Python pour le C."
Un dernier

2020-12-02 09:46 UTC, Seluj78 commented
Ping @PyDocTeur ?

2020-12-02 10:05 UTC, JulienPalard commented on extending/embedding.po
> +msgstr "Convertir les valeurs de l'appel Python pour le C."
```suggestion
msgstr "Convertir valeurs de l'appel Python pour le C."
```

2020-12-02 10:13 UTC, Seluj78 commented
ping

2020-12-02 10:13 UTC, Seluj78 commented
Ping?

2020-12-02 10:14 UTC, PyDocTeur commented
`DO NOT MERGE` ou `automerge` ? Je sais pas quoi faire là !

---
<details>
  <summary>Disclaimer</summary>

Je suis un robot fait par l'équipe de [l'AFPy et de Traduction](https://github.com/AFPy/PyDocTeur/graphs/contributors)
sur leur temps libre. Je risque de dire des bétises. Ne me blâmez pas, blamez les développeurs.

[Code source](https://github.com/afpy/pydocteur)

I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free
time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

(state: automerge_donotmerge)
`PyDocTeur v1.7.2`

</details>

2020-12-02 10:14 UTC, PyDocTeur commented
Y'a-il un humain dans le coin pour relire ? CC @Seluj78, @JulienPalard

---
<details>
  <summary>Disclaimer</summary>

Je suis un robot fait par l'équipe de [l'AFPy et de Traduction](https://github.com/AFPy/PyDocTeur/graphs/contributors)
sur leur temps libre. Je risque de dire des bétises. Ne me blâmez pas, blamez les développeurs.

[Code source](https://github.com/afpy/pydocteur)

I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free
time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

(state: automerge)
`PyDocTeur v1.7.2`

</details>

2020-12-02 10:15 UTC, Seluj78 commented
Ping

2020-12-03 12:46 UTC, Seluj78 approved these changes

2020-12-03 12:46 UTC, PyDocTeur commented
Ça part en merge, ne touchez à plus rien, je m'en occupe !

---
<details>
  <summary>Disclaimer</summary>

Je suis un robot fait par l'équipe de [l'AFPy et de Traduction](https://github.com/AFPy/PyDocTeur/graphs/contributors)
sur leur temps libre. Je risque de dire des bétises. Ne me blâmez pas, blamez les développeurs.

[Code source](https://github.com/afpy/pydocteur)

I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free
time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

(state: automerge_approved_testok)
`PyDocTeur v1.9.0`

</details>

2020-12-03 12:47 UTC, merged

2020-12-03 12:47 UTC, PyDocTeur commented
Génial ! Merci @JulienPalard pour cette contribution ! C'est fusionné.

---
<details>
  <summary>Disclaimer</summary>

Je suis un robot fait par l'équipe de [l'AFPy et de Traduction](https://github.com/AFPy/PyDocTeur/graphs/contributors)
sur leur temps libre. Je risque de dire des bétises. Ne me blâmez pas, blamez les développeurs.

[Code source](https://github.com/afpy/pydocteur)

I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free
time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

(state: automerge_approved_testok)
`PyDocTeur v1.9.0`

</details>